server:
  port: 8080
spring:
  application:
    name: product
  datasource:
    url: 'jdbc:postgresql://localhost:5432/product'
    username: 'welovemugsadmin'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'